let managerdetails={
    first:
    {
    name: "felio",
    Age: "56",
    Birthdate : "65-6-19",
    Gender:"male",
    Maritalstatus:"triple", 
    Nationality:'hind',
    address: "baheadr bad seyrick floor 19",
    cnicnumber:"1234567XXXXXX",
    dateofhire :"1-dec-2001",
    RelationshipInformation : "",
    JobHistory :"start 28 october - 3 -dec-19",
    Education :"CA",
    salaryDate : "2",
     terminatedate :"-", 
    socialSecurity : "none",
    Employment :"Type – Permanen",
    EmploymentStatus: "Active",
    DateofJoining : '1st April 2014',
     NameofBank :"ACME Corp",
    BankAccountnumber: "XXXXXXXXXX2018",
    Workweek :"– Monday to Friday",
     Lastdayofworking :"– NA"
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },
    secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    },secondmangerdetail:
    {
        name: "felio",
        Age: "56",
        Birthdate : "65-6-19",
        Gender:"male",
        Maritalstatus:"triple", 
        Nationality:'hind',
        address: "baheadr bad seyrick floor 19",
        cnicnumber:"1234567XXXXXX",
        dateofhire :"1-dec-2001",
        RelationshipInformation : "",
        JobHistory :"start 28 october - 3 -dec-19",
        Education :"CA",
        salaryDate : "2",
         terminatedate :"-", 
        socialSecurity : "none",
        Employment :"Type – Permanen",
        EmploymentStatus: "Active",
        DateofJoining : '1st April 2014',
         NameofBank :"ACME Corp",
        BankAccountnumber: "XXXXXXXXXX2018",
        Workweek :"– Monday to Friday",
         Lastdayofworking :"– NA"  
    }


},
